# TLS and basic authentication configuration example.
#
# Additionally, a certificate and a key file are needed.
tls_server_config:
  cert_file: "C:/prometheus/windows_exporter/server.crt"
  key_file: "C:/prometheus/windows_exporter/server.key"

# Usernames and passwords required to connect.
# Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt.
# create with: htpasswd -nBC 10 "" | tr -d ':\n'
basic_auth_users:
  basicAuthUser: basicAuthPassword
